// Generated by gencpp from file shibie/IdentifyRequest.msg
// DO NOT EDIT!


#ifndef SHIBIE_MESSAGE_IDENTIFYREQUEST_H
#define SHIBIE_MESSAGE_IDENTIFYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shibie
{
template <class ContainerAllocator>
struct IdentifyRequest_
{
  typedef IdentifyRequest_<ContainerAllocator> Type;

  IdentifyRequest_()
    : call()  {
    }
  IdentifyRequest_(const ContainerAllocator& _alloc)
    : call(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _call_type;
  _call_type call;





  typedef boost::shared_ptr< ::shibie::IdentifyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shibie::IdentifyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IdentifyRequest_

typedef ::shibie::IdentifyRequest_<std::allocator<void> > IdentifyRequest;

typedef boost::shared_ptr< ::shibie::IdentifyRequest > IdentifyRequestPtr;
typedef boost::shared_ptr< ::shibie::IdentifyRequest const> IdentifyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shibie::IdentifyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shibie::IdentifyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::shibie::IdentifyRequest_<ContainerAllocator1> & lhs, const ::shibie::IdentifyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.call == rhs.call;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::shibie::IdentifyRequest_<ContainerAllocator1> & lhs, const ::shibie::IdentifyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace shibie

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::shibie::IdentifyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shibie::IdentifyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shibie::IdentifyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shibie::IdentifyRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shibie::IdentifyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shibie::IdentifyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shibie::IdentifyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3215900da2c21797ec453ce12acd7b3";
  }

  static const char* value(const ::shibie::IdentifyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3215900da2c2179ULL;
  static const uint64_t static_value2 = 0x7ec453ce12acd7b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::shibie::IdentifyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shibie/IdentifyRequest";
  }

  static const char* value(const ::shibie::IdentifyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shibie::IdentifyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string call\n"
;
  }

  static const char* value(const ::shibie::IdentifyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shibie::IdentifyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.call);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IdentifyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shibie::IdentifyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shibie::IdentifyRequest_<ContainerAllocator>& v)
  {
    s << indent << "call: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.call);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHIBIE_MESSAGE_IDENTIFYREQUEST_H
