// Generated by gencpp from file shibie/IdentifyResponse.msg
// DO NOT EDIT!


#ifndef SHIBIE_MESSAGE_IDENTIFYRESPONSE_H
#define SHIBIE_MESSAGE_IDENTIFYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shibie
{
template <class ContainerAllocator>
struct IdentifyResponse_
{
  typedef IdentifyResponse_<ContainerAllocator> Type;

  IdentifyResponse_()
    : back()  {
    }
  IdentifyResponse_(const ContainerAllocator& _alloc)
    : back(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _back_type;
  _back_type back;





  typedef boost::shared_ptr< ::shibie::IdentifyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shibie::IdentifyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IdentifyResponse_

typedef ::shibie::IdentifyResponse_<std::allocator<void> > IdentifyResponse;

typedef boost::shared_ptr< ::shibie::IdentifyResponse > IdentifyResponsePtr;
typedef boost::shared_ptr< ::shibie::IdentifyResponse const> IdentifyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shibie::IdentifyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shibie::IdentifyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::shibie::IdentifyResponse_<ContainerAllocator1> & lhs, const ::shibie::IdentifyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.back == rhs.back;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::shibie::IdentifyResponse_<ContainerAllocator1> & lhs, const ::shibie::IdentifyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace shibie

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::shibie::IdentifyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shibie::IdentifyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shibie::IdentifyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shibie::IdentifyResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shibie::IdentifyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shibie::IdentifyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shibie::IdentifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4a1d3ec3f5c241f65fed707d363d25e";
  }

  static const char* value(const ::shibie::IdentifyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4a1d3ec3f5c241fULL;
  static const uint64_t static_value2 = 0x65fed707d363d25eULL;
};

template<class ContainerAllocator>
struct DataType< ::shibie::IdentifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shibie/IdentifyResponse";
  }

  static const char* value(const ::shibie::IdentifyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shibie::IdentifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string back\n"
;
  }

  static const char* value(const ::shibie::IdentifyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shibie::IdentifyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.back);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IdentifyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shibie::IdentifyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shibie::IdentifyResponse_<ContainerAllocator>& v)
  {
    s << indent << "back: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.back);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHIBIE_MESSAGE_IDENTIFYRESPONSE_H
