// Generated by gencpp from file shibie/Yolox_action.msg
// DO NOT EDIT!


#ifndef SHIBIE_MESSAGE_YOLOX_ACTION_H
#define SHIBIE_MESSAGE_YOLOX_ACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shibie
{
template <class ContainerAllocator>
struct Yolox_action_
{
  typedef Yolox_action_<ContainerAllocator> Type;

  Yolox_action_()
    : action(0)  {
    }
  Yolox_action_(const ContainerAllocator& _alloc)
    : action(0)  {
  (void)_alloc;
    }



   typedef uint8_t _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::shibie::Yolox_action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shibie::Yolox_action_<ContainerAllocator> const> ConstPtr;

}; // struct Yolox_action_

typedef ::shibie::Yolox_action_<std::allocator<void> > Yolox_action;

typedef boost::shared_ptr< ::shibie::Yolox_action > Yolox_actionPtr;
typedef boost::shared_ptr< ::shibie::Yolox_action const> Yolox_actionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shibie::Yolox_action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shibie::Yolox_action_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::shibie::Yolox_action_<ContainerAllocator1> & lhs, const ::shibie::Yolox_action_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::shibie::Yolox_action_<ContainerAllocator1> & lhs, const ::shibie::Yolox_action_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace shibie

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::shibie::Yolox_action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shibie::Yolox_action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shibie::Yolox_action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shibie::Yolox_action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shibie::Yolox_action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shibie::Yolox_action_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shibie::Yolox_action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1d6170759a11ac69d62121271b22bc9";
  }

  static const char* value(const ::shibie::Yolox_action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1d6170759a11ac6ULL;
  static const uint64_t static_value2 = 0x9d62121271b22bc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::shibie::Yolox_action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shibie/Yolox_action";
  }

  static const char* value(const ::shibie::Yolox_action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shibie::Yolox_action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 action\n"
;
  }

  static const char* value(const ::shibie::Yolox_action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shibie::Yolox_action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Yolox_action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shibie::Yolox_action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shibie::Yolox_action_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHIBIE_MESSAGE_YOLOX_ACTION_H
